### ISSUE TITLE
PageBuilder

### ISSUE THREAD

**Issue by nibra** [joomla-projects/joomla-pythagoras#113]
### Existing Solutions

Currently, a lot of tools (partially) implementing this idea are emerging.
- [SP Page Builder](https://www.joomshaper.com/page-builder)
- [JSN PageBuilder](https://www.joomlashine.com/joomla-extensions/jsn-pagebuilder-joomla-page-builder-extension.html)
- [Quix Pagebuilder](https://www.themexpert.com/quix-pagebuilder)
- [Gridbox](http://www.balbooa.com/gridbox)
- [Azura - Responsive Joomla Page Builder](http://codecanyon.net/item/azura-responsive-joomla-page-builder/8658367)
- [PageBuilder CK](https://www.joomlack.fr/en/joomla-extensions/page-builder-ck)
- [NextGenEditor](http://nextgeneditor.com/index.php/en/)
- [Yootheme Pro](http://yootheme.com/blog/2016/09/01/yootheme-pro)
- [Divi Builder](www.elegantthemes.com/blog/theme-releases/divi-3) (Wordpress)
- [JA Builder](http://demo.builder.joomlart.com/)

Some design guidelines (iOS, Material, ...) contain element definitions, that might be re-used here. A collection of such guidelines was published by [Design Guidelines.](http://designguidelines.co/index.html)

## Initial Attempt to Produce Visible Output

PR #117 adds page handling. It uses the data structures of the `PageBuilder` (which's GUI still is to be created).

### Installation

> _Note:_ Be sure to run `composer install` after checkout!

The PR includes a primitive installer, that resolves relations between entities and builds up the database. The following command deletes the database and the compiled entity definitions, and rebuilds them:

``` bash
$ ./install.sh
```

This step is currently only needed before the first run, and when you manually add data records to the extensions' sample data.

### Run the Demo

The installation is designed to be run using `docker-compose`:

``` bash
$ docker-compose up -d
```

In your browser, head to `http://localhost:8080/index.php` and pick an item from the menu, or go to `http://localhost:8080/index.php/admin/pagebuilder` to see a (not yet functional) prototype of the PageBuilder.

However, currently only the `web` container is used, so you should be able to run the demo without `docker-compose`, if you have a web server installed and your source directory is accessible for it.

### Enitities and Elements

Since both are called `ContentTypes` from time to time, it is necessary to distinuish those two.
**Entities** mostly respond to database records. **Elements** are components of a page, and thus subject for layout and styling.

PR #117 added basic elements, like image or headline, as well as 'active' elements, like slider or accordion. The `PageBuilder` itself delivers an example of a custom element, the `TemplateSelector`. It shows how you can compose your custom elements from the existing elements.

**Comment by ufuk-avcu** [comment]
Yootheme Pro - A new player in the Pagebuilder / Websitebuilder Market. Not released yet. http://yootheme.com/blog/2016/09/01/yootheme-pro

**Comment by nibra** [comment]
Thank you, @ufuk-avcu, added it to the list.

**Comment by ciar4n** [comment]
One of the more impressive examples not on the list is 'JA Builder' from Joomlart (still in beta)... https://www.joomlart.com/blog/ja-site-builder-new-demo-with-more-features-and-improvements

Online Demo: http://demo.builder.joomlart.com/

**Comment by nibra** [comment]
Thank you, @ciar4n, added it to the list.

**Comment by nibra** [comment]
Moved to [Projects](https://github.com/joomla-projects/joomla-pythagoras/projects) page
