### ISSUE TITLE
JApplicationWeb::detectRequestUri() should not rely on array members to exist

### ISSUE THREAD

**Issue by nibra** [joomla-projects/joomla-pythagoras#2]
`JApplicationWeb::detectRequestUri()` relies on `$_SERVER['HTTP_HOST']` (and others) to be set.
External data should _always_ be validated or sanitized.

**Comment by wilsonge** [comment]
Run it through `JInput` I guess. FWIW I think a lot of this code is duplicated by that in `JUri` anyhow (see the methods left in `JUri` at https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/uri/uri.php#L81) which require pretty much the same server vars

**Comment by wilsonge** [comment]
https://github.com/joomla-framework/application/pull/44 PR to the framework. We just need to do the same thing in the CMS

**Comment by nibra** [comment]
Great! By the way - how do send pull requests from here to the CMS? Do I really have to have 2 upstreams defined in my local repo (one to this repo, one to my CMS fork)?

**Comment by wilsonge** [comment]
What's here and in the CMS is probably going to diverge pretty quickly - so I'd just have two different repos set up. But yeah I have two different remotes in my repo whilst I'm still merging in the CMS repo

**Comment by nibra** [comment]
Should we have a 'backport' branch then, for things that can go into 3.x without BC?

**Comment by wilsonge** [comment]
Can do

**Comment by wilsonge** [comment]
I think we've done this now so closing this issue
