### ISSUE TITLE
JRouter::setVars() should be split up into two methods

### ISSUE THREAD

**Issue by nibra** [joomla-projects/joomla-pythagoras#3]
For better readability of code, the second argument of `JRouter::setVars()` should be omitted.
`JRouter::setVars($arr)` for non-merge mode and `JRouter::addVars($arr)` for merge mode are proper names.

**Comment by mbabker** [comment]
Let's add `addVars` in 3.5 so the new API exists and we can deprecate the dual functionality at that point and fully drop it with 4.0.

**Comment by laoneo** [comment]
@wilsonge is this issue planed for Joomla 4? Or can it even be done on a Joomla 3 minor release?

If yes, @nibra  can you please open (or transfer) this issue on (to) the CMS repo. It should be assigned then to the relevant milestone.

I'm closing this one as it is not relevant for Joomla X.
