### ISSUE TITLE
[RFC] Dealing with extension namespaces

### ISSUE THREAD

**Issue by nikosdion** [joomla-projects/joomla-pythagoras#36]
# The problem

All Joomla! 4 extensions (components, plugins, modules, templates, libraries) will be namespaced in Joomla! 4. In Denmark we discussed the namespacing rules. We also implied that all extensions will follow PSR-4 naming conventiosn for their files. However, in order to be complete, we need to
- have a way to get the root namespace for an extension
- tell the PSR-4 autoloader where to look for these files
  In this RFC I'm proposing a way to deal with both issues elegantly. This also solves all namespace-related questions which have been raised time and again, e.g. how do I locate a command object when all I know is the component's name.
# Steps to the solution
## XML Manifest

All Joomla! extensions need an XML manifest to be installed. The manifest contains all sorts of information, from the name of the extension and its metadata to its configuration. I propose adding a mandatory tag `<namespace>` in the same level as `<version>`. The syntax of this tag would be:

``` xml
<namespace><![CDATA[AcmeCorp\Anvil]]></namespace>
```

This means that the extension is under the `AcmeCorp\Anvil` namespace.
## `#__extensions` table column

I propose adding a new column `namespace` to the `#__extensions` table. This will hold the contents of the `<namespace>` tag defined in the XML Manifest file.
## Priming the autoloader on application startup

The autoloader can be primed at the constructor of the application, right after reading its configuration (or at the very beginning if we end providing a Configuration service through a DI Container passed to the application / a Configuration object passed to the constructor while bulding the application object through the DI Container).

At this point, we do a simple select of all enabled extensions, e.g.

``` sql
SELECT
    type, element, folder, client_id, namespace
FROM
    #__extensions
WHERE
    enabled = 1
```

Using this information we know the namespace and the filesystem path to each extension. Therefore we can do something like

``` php
$loader = require JPATH_LIBRARIES . '/composer_autoload.php';

foreach ($extensions as $extension)
{
    $namespace = $extension->namespace;

    // Get the absolute filesystem path for this extension
    $path = $this->getExtensionPath($extension);

    $loader->setPsr4($namespace, $path)
}
```

Furthermore the application should cache the link between an extension's name and its namespace and path. This would allow us to locate classes and files when all we know is the extension's name, i.e. the most common use case in the real world.

**Comment by wilsonge** [comment]
This looks awesome. One question. How will libraries work that may contain other namespaced code (e.g. I have a library at work which hooks into google analytics api with my own custom code to run with it?)

**Comment by mbabker** [comment]
So not totally related to this RFC as written, but something we should consider in some form later is the ability to generate a cached loader with all the lookup paths in place, unless that's going to be too much of a strain on our resources/codebase.

**Comment by nikosdion** [comment]
@wilsonge Your library in this case would have a class which acts as the entry point to your implementation. At this stage you have to options:
- Use Composer (which is a major PITA in mass distributed code)
- Add a PSR-4 map in the entry point to your library's implementation
  I would choose the latter, having been scalded by the first on several occasions.

**Comment by nikosdion** [comment]
@mbabker I agree with this. When an extension is added / removed / published / unpublished we could generate a static .php file which can be loaded as soon as the composer's autoloader is up. This has the benefit of being able to replace even core code or Composer dependencies with custom code. The only drawback is that if this file is not writeable, we are screwed. That's why I chose the less efficient database route ;)

**Comment by mbabker** [comment]
Ya we'd need a good API to account for that, but in an ideal world, it'd be a great add-on to this initial approach.

**Comment by nibra** [comment]
@nikosdion If the file cannot be written due to odd permissions, it can be handled like the `configuration.php`. The admin gets a warning about that, and the opportunity to repair it manually by either upload that file or regenerate it after permission fix (preferred).

**Comment by nikosdion** [comment]
@nibra It's more serious than configuration.php being unwriteable. If the configuration.php cannot be written to your site still works. Also, it's feasible to manually edit the file blindly following someone else's instructions (as a several dozens of my clients can tell you). However, if the PSR-4 map file cannot be written to then your site may instantly die, e.g. if the root namespace of a plugin or module has changed. This could even prevent the error message from appearing!

That said, I can think of a possible mitigation strategy.

IF the map file is not present OR if a configuration.php switch is set THEN do not load the map at this point. Instead, defer loading to the application initialisation, calculating the map on the fly per this RFC.

Even better, if the file is unwriteable refuse to permit extension installation, update, publish or unpublish until either the file is writeable or the configuration.php switch is set. This will prevent unexpected white pages which will frustrate our less technically inclined users, i.e. the bulk of our user base.

**Comment by nibra** [comment]
The latter makes more sense, as the first approach would not protect against an outdated file.Actually, I like the approach.

**Comment by nikosdion** [comment]
They are meant to be complementary. You can have two failure modes: file not present or file outdated. The former is trivial to detect (file_exists). The second one not at all. You have to prevent this from happening, hence not allowing extension install/update/status change under conditions which are known to trigger this failure mode.

The switch is only necessary to provide a mitigation mode for those servers where the writeable status of the file cannot be changed immediately (you wouldn't believe some Windows hosts...) but the user MUST be able to change the status or install/update an extension. For example a plugin is causing a massive issue on the live site and the admin has to disable it a.s.a.p. despite the unwriteable status of the PSR-4 map file.

You can never be too paranoid with these things :)

**Comment by nibra** [comment]
Doesn't it make sense then, to be always on the safe side and access the database? Performance could be improved by creating an in-memory view of the extension table subset. (Just thinking loud)

**Comment by nikosdion** [comment]
No, you didn't get the idea right.

A. Normally, we use the cache file. This is the standard mode for 99% of the cases.
B. If the cache file is not present we access the database.
C. If the configuration.php flag is set we access the database.

B is a safeguard against someone stupidly removing the cache file because, ugh, _people_.
C is a safeguard against an unwriteable cache file or otherwise having screwed up so badly you have no idea how to make the damn thing work because, ugh, _hosts and people_

In-memory VIEWs sound great...

...until you get to use the run-of-the-mill El Cheap-o Craphost™ for $1.99 per month. Then you find out that in memory VIEWs are forbidden, like MEMORY tables, because the cheap bastard running the host tries to cram 1000-3000 sites on a single not-exactly-top-spec machine and they can't afford to give you memory. Also typical on this server is PHP memory limits of 64Mb or less – not uncommon to see 32Mb in the year 2015 on these hosts, I kid you not. That's why I didn't even say anything about database VIEWs (besides, you'd actually need a MEMORY table, not a VIEW, since you don't and MUST NOT have the absolute path data in a table).

**Comment by nibra** [comment]
I understand the concept. I'm just not sure, if the performance gain is worth the efford. It is one cacheable database query vs. one filesystem access in the best case.

On the other hand, I guess you have some code ready for that already from your FOF scaffolding, so the efford is maybe not as big as I think.

**Comment by nikosdion** [comment]
If it was one FS access vs one DB access I wouldn't be discussing it ;) What takes most of the execution time is calculating file paths for each extension (we'll have an average of 150 enabled extensions per site, maybe more considering horizontal components). That's quite a lot of time.

On the other hand, FS access may be entirely unnecessary since PHP 5.5 has opcache enabled by default. Therefore including the map file will return results from the cache. We just have to remember to bust the opcache when we are regenerating the file. That's trivial.

Considering all these I believe the cache file to be much faster than DB access + computing paths.

**Comment by nibra** [comment]
I see. I fully trust your experience in that area.
