### ISSUE TITLE
Media Manager

### ISSUE THREAD

**Issue by nibra** [joomla-projects/joomla-pythagoras#42]
Sub tasks:
- client-side image resizing
- SVG support
- Use Buddhima code as a starting point
- FlySystem support

[Related issues](https://github.com/joomla/joomla-cms/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+media+manager) in the CMS repository

**Comment by wilsonge** [comment]
Several PR's have done some work for 3.x already which we should test, merge and port back to this repo before we start work so as not to duplicate work

https://github.com/joomla/joomla-cms/pull/7646
https://github.com/joomla/joomla-cms/pull/7810
https://github.com/joomla/joomla-cms/pull/7435

**Comment by laoneo** [comment]
An improved media manager is planed for either Joomla 3.7 or 4 according to the PLT report https://volunteers.joomla.org/reports/245-plt-meeting-after-j-and-beyond-2016.
