### ISSUE TITLE
Namespaces everywhere

### ISSUE THREAD

**Issue by nibra** [joomla-projects/joomla-pythagoras#45]
@todo: Add description.

**Comment by nikosdion** [comment]
This is almost done thanks to the work of @wilsonge and @mbabker 

According to @wilsonge we need about a man-week to complete this work for all library classes except JForm (which will be refactored anyway with gh-55).

**Comment by mbabker** [comment]
JHtml is another one that's going to be tricky to do until we can remove the `_` method.  We can use the code from the Framework's form package as a starting point to cope with building namespaced classes as it uses a similar dot string notation.

**Comment by rdeutz** [comment]
Namespaces  40h
- cms/Jhtml
- cms/Jtable
- cms/helper
- Jform (see JForm Refactoring #55 )

**Comment by wilsonge** [comment]
There are more in the /Joomla folder as well todo. E.g JDocument. However majority of them are framework packages

**Comment by laoneo** [comment]
Closing it as we have a PR #69 for it.
