### ISSUE TITLE
DI Container

### ISSUE THREAD

**Issue by nibra** [joomla-projects/joomla-pythagoras#47]
-  Start the application with a container 8h
-  Deprecate JFactory 8h
-  Backport it to J 3.x 24h
-  Adapt the Unit Tests 40h

There is already the PR #63  for it.

**Comment by nikosdion** [comment]
Time estimate: 1 man-week

**Comment by rdeutz** [comment]
* Start the application with a container 	8h
* Deprecate JFactory 	8h
* Backport it to J 3.x 	24h
* Adapt the Unit Tests	40h

**Comment by laoneo** [comment]
Done https://github.com/joomla-projects/joomla-pythagoras/blob/clean-base/index.php#L21
