### ISSUE TITLE
Orthogonal system implementation

### ISSUE THREAD

**Issue by nikosdion** [joomla-projects/joomla-pythagoras#5]
Following our conversation with @nibra about the orthogonal system, I have some ideas we need to discuss about the implementation.

The implementation requires us to raise events from the Commands and Models (and possibly the renderer – pending the presentation of a renderer example to fully grasp it). This means that the implementation depends on the MVC being done before we begin. Otherwise I can only test and create the event dispatcher which is only a quarter of the job required (and barely half a sprint). So I guess this work has to be moved to a later sprint and I could probably start working on JForm instead, beginning next week – this week I need to set up a functioning working environment after Apple screwed me over.

Therefore I need your input on whether we should start half-implementing this on Sprint 1 or put MVC as a dependency on it.

Regarding the implementation, I think our events will need to be passed two things: Context and Options.

Context would need to provide us with at least the following:
- Extension name, e.g. "com_example"
- Container of the extension (maybe this makes extension name obsolete, depending on whether the Container also provides scalars, e.g. like Pimple or through a Registry object)
- Origin. "command", "model" or null when not applicable. For com_example's Items model this would be "model"
- Origin Name. The name of the Origin raising the event. For com_example's Items model this would be "Items".

Why? The context allows orthogonal components (implemented as the event handlers we call "Plugins") AND our event handler to know whether to process an event. For example, an orthogonal component told not to fire for the Login view of com_users could examine the Extension Name, Origin and Origin Name to return immediately. Or we could even have the event handler do that automatically to make things more DRY.

So, I guess we need a Context object – and that's the second item I need your input on.

As far as the Options go this is what we're already passing in (existing Plugins') events. However, I would prefer passing a hash array instead of calling the event with an array and then exploding it into parameters for use in call_user_func. Why a hash array? It makes things less ambiguous. It's a poor man's implementation of how Objective-C and Swift handle functions (and events). By forcing the developer to specify the name of the variable they are passing instead of implying it by position you have multiple benefits:
- Self documenting code. A developer reading her code 6 months later can still understand what is going on.
- Forwards compatibility: you can add/remove parameters without messing things up too much. Also, you can deprecate the parameter list in favour of a new one and still do automatic mapping for legacy code.
- Cross checking. The developer can check that her code passes the correct parameters. The event handler can also detect missing required parameters and raise InvalidArgument exceptions which can be caught, traced and debugged in seconds instead of Fatal errors which become Really Hairy Monsters to debug.

Why not use an Options object, e.g. a Registry? Performance. Registry is just a convenience wrapper around a nested hashed array. Plain stdClass implementations are generally going to be written as `(object)['foo' => $bar]` so what's the reason of inflicting performance loss besides looking like a cool kid?

So, that's the third item I want your input on.

**Comment by wilsonge** [comment]
For the options object if we don't want to go as far as Registry maybe PHP's ArrayObject would be better? There's still a bit more overhead than native stdClass but implementing ArrayAccess gives you a lot more flexibility

**Comment by nikosdion** [comment]
In theory using ArrayObject sounds good, in practice I can't see any benefits. Why go through offsetExists and offsetGet when I can simply do `isset($options['something'])` and `$x = $options['something'];`? Not to mention the simple array access is faster and we're talking about hundreds to thousands of events per page.

**Comment by nibra** [comment]
> This means that the implementation depends on the MVC being done before we begin

Yes and no. From the design point of view, the events can as well be defined at the listener side, and get implemented into the MVC, when we get there. This approach may even lead to a better MVC, as it will be designed with specific requirements.

> Regarding the implementation, I think our events will need to be passed two things: Context
> and Options.

The information about where the event came from, is best provided by the caller itself.

```
$dispatcher->trigger('eventName', $this, $options);
```

The event handler will then decide based on the callers class, if and how to handle. In most cases I can think of, relevant information can be asked from the caller.

> As far as the Options go this is what we're already passing in (existing Plugins') events.

Ideally, an event specific Parameter object is used, e.g., `EventNameParameters`. It can contain not only the data not available from the caller (which should not be much), but also default values and validation / sanitation. Thus listeners do not have to care about sanity and integrity themselves. I believe, that this balances the performance impact _and_ gives better overall security.

**Comment by nikosdion** [comment]
> Yes and no. From the design point of view, the events can as well be
> defined at the listener side, and get implemented into the MVC, when we get
> there. This approach may even lead to a better MVC, as it will be designed
> with specific requirements.
> 
> OK, I already know how to do that for a generic Controller / Command
> (really: the event simply interpolates the task / Command name with a fixed
> string, dead simple), a generic Model and a data-aware _Model implementing
> an Active Record pattern_ (something like Laravel's Eloquent to be more
> specific). I suppose we're going to stick to that pattern? I'm not sure
> what events an ORM, for example, would let us raise. At the very least it
> should let us raise events on save / create / status change / pre-save
> check etc so the events SHOULD be reusable between an Active Record model
> and an ORM solution. I hope? :D

The other missing piece for me is the View which is now going to be
replaced. I have not a good idea how that will work so I think I'll let you
define the events for that.

> The information about where the event came from, is best provided by the
> caller itself.
> 
> $dispatcher->trigger('eventName', $this, $options);
> 
> This is how I'm doing it in FOF 3 :) The downside is that I have to go
> through a few object iterations, e.g.

$component = $eventSource->getContainer()->componentName;
$originName = $eventSource->getName();

I didn't have an origin since my handler was non-generic, but I would have
to do it the stupid way lacking another common interface:

$origin = 'other';
if ($eventSource instanceof Model) $origin = 'model';
if ($eventSource instanceof Controller) $origin = 'controller';

This all seems like lots of duplicated code to me. The triggerEvent already
has access to this information and can construct a Context object instead
of having the same bits of code repeated on every event handler. Hence my
suggestion. The other way is to have a helper to extract the context
information from an eventSource but I'm not very much in favour of
Superglobal Black Boxes a.k.a. Helpers any more.

> As far as the Options go this is what we're already passing in (existing
> Plugins') events.
> 
> Ideally, an event specific Parameter object is used, e.g.,
> EventNameParameters. It can contain not only the data not available from
> the caller (which should not be much), but also default values and
> validation / sanitation. Thus listeners do not have to care about sanity
> and integrity themselves. I believe, that this balances the performance
> impact _and_ gives better overall security.
> 
> OK, I agree. Much better. Having getter/setter method would help plenty.

If we want to be religious about it each event handler should expect an
object adhering to an event-specific Interface and have a default class
implementation. I'm thinking about how Guzzle 3 (yeah, I know, old version,
that's what I am familiar with) deals with event handling. Makes sense?

**Comment by nibra** [comment]
> If we want to be religious about it each event handler should expect an object adhering to an event-specific Interface and have a default class implementation. I'm thinking about how Guzzle 3 (yeah, I know, old version, that's what I am familiar with) deals with event handling. Makes sense?

Yes. That interface (resp. implementing object) could as well carry the event source information, right?

**Comment by nibra** [comment]
> The other missing piece for me is the View which is now going to be replaced. I have not a good idea how that will work so I think I'll let you define the events for that.

Each `visit<ContentType>` method can raise `onBeforeRender<ContentType>` / `onAfterRender<ContentType>` events. We should find a way to enforce these events for custom renderers, like the `CommandProcessor` does for commands

Events at the start and end of the render process as a whole are possible as well (`onBeforeRender`, `onAfterRender`).

**Comment by nikosdion** [comment]
Yes. That interface (resp. implementing object) could as well 
carry the event source information, right? 
Yes, indeed. We may even create an abstract class which 
extracts the information from the event source object. So we 
could probably have specialised event handlers extend from 
this abstract class and implement the event-specific 
Interface. I need to think a bit about it though. Something is 
nagging me about this approach being too tightly coupled.

**Comment by nikosdion** [comment]
Each visit<ContentType> method can raise 
onBeforeRenderContentType / onAfterRenderContentType events. 
We should find a way to enforce these events for custom renderers, 
like the CommandProcessor does for commands 
Events at the start and end of the render process as a whole are 
possible as well (onBeforeRender, onAfterRender).
Ah! So, the event source would be the renderer itself. So the handler 
would have access to both the rendering context and the renderer, 
therefore able to modify the output in any way imaginable. Got it!

**Comment by nibra** [comment]
> Ah! So, the event source would be the renderer itself. So the handler would have access to both the rendering context and the renderer, therefore able to modify the output in any way imaginable. Got it!

Exactly.

**Comment by nibra** [comment]
> Yes, indeed. We may even create an abstract class which extracts the information from the event source object. So we could probably have specialised event handlers extend from this abstract class and implement the event-specific Interface. I need to think a bit about it though. Something is nagging me about this approach being too tightly coupled.

Best is interfaces + traits (as in PSR Logger), i think.

**Comment by nikosdion** [comment]
Best is interfaces + traits, i think. 
I agree. Much better approach.

**Comment by nikosdion** [comment]
This branch is currently on hold since we're going to implement a Service layer. In this case the orthogonal implementation will be dependent on this layer's command bus. For now the only thing that can (and should) be used from this branch is the Event package refactoring and all the related refactors (JPlugin, JEditor, JCaptcha).
