### ISSUE TITLE
Decouple com_finder

### ISSUE THREAD

**Issue by nibra** [joomla-projects/joomla-pythagoras#50]
The following need to be removed from Joomla! and become a separate package in the same way com_weblinks was removed:

```
Smart Search - Tags plugin
Smart Search - Categories plugin
Smart Search - Contacts plugin
Smart Search - Content plugin
Smart Search - News Feeds plugin
Smart Search front-end module
Smart Search component
```

The biggest question regarding time budgeting is how exactly the new package is going to be disseminated. So I'd say 24 man-hours, about 20 of which is going back and forth with the organization until we figure out how to distribute the package.

**Comment by nikosdion** [comment]
The following need to be removed from Joomla! and become a separate package in the same way com_weblinks was removed:

* Smart Search - Tags plugin
* Smart Search - Categories plugin
* Smart Search - Contacts plugin
* Smart Search - Content plugin
* Smart Search - News Feeds plugin
* Smart Search front-end module
* Smart Search component

The biggest question regarding time budgeting is how exactly the new package is going to be disseminated. So I'd say 24 man-hours, about 20 of which is going back and forth with the organization until we figure out how to distribute the package.

**Comment by laoneo** [comment]
@wilsonge is this issue planed for Joomla 4? Or can it even be done on a Joomla 3 minor release?

If yes, @nibra can you please open (or transfer) this issue on (to) the CMS repo. It should be assigned then to the relevant milestone.

I'm closing this one as it is not relevant for Joomla X.

**Comment by wilsonge** [comment]
We have a whole section on the decoupling on the logistical side of things (See the decoupling section: https://volunteers.joomla.org/reports/245-plt-meeting-after-j-and-beyond-2016 ) - the version this happens in is kinda irrelevant - it's done when the release work behind it is done, there's a suitable way to maintain the core components and we have a way of making sure we have core distributed that isn't completely empty putting off end users.

**Comment by nibra** [comment]
Closing without moving to `joomla/joomla-cms`, since decoupling is in progress already.
