### ISSUE TITLE
Logger

### ISSUE THREAD

**Issue by nibra** [joomla-projects/joomla-pythagoras#61]
Add PSR-3 compatible logging functionality.

**Comment by laoneo** [comment]
@wilsonge is this issue planed for Joomla 4? Or can it even be done on a Joomla 3 minor release?

If yes, @nibra can you please open the same issue on the CMS repo.

**Comment by wilsonge** [comment]
We definitely can't do it in 3.x and stay b/c with JLog and it doesn't really make sense to have two loggers there until we know 100% what we're plumping for in J4. I need to have a think about this first before I give a definite answer

**Comment by nibra** [comment]
Closing without moving to `joomla/joomla-cms`, since there's no meat on this issue.
