### ISSUE TITLE
Session API usage

### ISSUE THREAD

**Issue by mbabker** [joomla-projects/joomla-pythagoras#62]
The manner in which the application uses the session should be refactored.  Key issues:
- `JApplicationCms::__construct()` codes a default behavior to use sessions which are manually started in the constructor's context; the `loadSession()` method should be extracted into a service provider and the call to `$session->start()` removed from the application's bootup sequence
- `JApplicationCms::checkToken()` forces a session record to be written to the `#__session` table regardless of the session handler type
- `JApplicationCms::checkToken()` also performs functions that belong to the session handler's garbage collection mechanism (see ignored PR https://github.com/joomla/joomla-cms/pull/6608)

**Comment by nibra** [comment]
Moved to [joomla/joomla-cms#10746](https://github.com/joomla/joomla-cms/issues/10746)
