### ISSUE TITLE
Remove FOF 2

### ISSUE THREAD

**Issue by laoneo** [joomla-projects/joomla-pythagoras#66]
FOF needs to be removed in J4 in favor of the new architecture and to not confuse developers to have multiple ways to build their extensions..

How should FOF being deprecated in Joomla 3? Would it be enough to add a deprecate message in that file https://github.com/joomla/joomla-cms/blob/staging/libraries/fof/include.php as it would be too much effort to add a deprecate message to every single file?

**Comment by dgrammatiko** [comment]
I think it is already deprecated, just do pr that removes the folder and the composer stuff...

**Comment by dgrammatiko** [comment]
Also mind https://github.com/joomla/joomla-cms/blob/staging/libraries/cms.php#L42-L46

**Comment by zero-24** [comment]
@dgt41 we have core functions that works with fof postinstall & TFA they will stop working also. Fof is also in the com_admin script (cleaning the fof cache)

**Comment by nikosdion** [comment]
com_postinstall needs to be rewritten – if we're keeping it at all. Most users ignore the messages anyway.

TFA only uses the TOTP library in FOF. You can simply pry it away from FOF and put it in libraries/cms

As for clearing the fof cache, obviously this is no longer an issue if you remove FOF ;)

**Comment by mbabker** [comment]
Ironically some people do read them.  A lot of questions on the forum after 3.4.0 after the robots.txt and htaccess changes.

**Comment by zero-24** [comment]
yes i just what to mention that it is not only remove the `fof` folder.

**Comment by nikosdion** [comment]
Amazing. So this feature I first tried on my software and ported to Joomla! actually worked on Joomla! far better than it worked on my own software? LOL!

**Comment by wilsonge** [comment]
It's just scaleability dude :P More Joomla Users = More people asking questions :P

**Comment by laoneo** [comment]
With the clean base approach, this becomes obsolete.
