### ISSUE TITLE
Remove unused language strings

### ISSUE THREAD

**Issue by Bakual** [joomla-projects/joomla-pythagoras#67]
Not sure if that is covered already somewhere but there are quite a few language strings which are not used anymore within Joomla 3. Those can be removed with J4.

There is a tool written by @aDaneInSpain which can help to find those unused strings
See https://github.com/Jensen-Technologies/Find-Unused-Joomla-Language-Constants

**Comment by GABBAR1947** [comment]
https://github.com/joomla-projects/joomla-pythagoras/pull/80

**Comment by nibra** [comment]
This is covered in the `joomla/joomla-cms` repo with an in-depth discussion.
