### ISSUE TITLE
Orthogonal features

### ISSUE THREAD

**Issue by jochendaum** [joomla-projects/joomla-pythagoras#74]
I like the idea of orthogonal features and want to show some use cases, which show the value in them:

Long living Joomla data: Most sites I come in contact with have a long to very long history, spanning from Joomla 1.5 sometimes 1.0. Because of this often users are in there, which are no longer involved, but need to be kept, so that historical data is accurate. Archival of users would be very helpful here.

The same reasoning can be applied to archival of anything else, in any extension.

There should also be a sunset time for extensions implementing these features, and/ or it should be shown in the extension manager if they support archival and tagging

**Comment by nibra** [comment]
Because of the orthogonal architecture, extensions will no longer need to implement these features; the features will be provided automatically, as long as the extensions use the new architecture properly.

No action required, closing.

**Comment by jochendaum** [comment]
Ok, so is Archival an orthogonal feature?

**Comment by nibra** [comment]
Yes, because it is a cross concern, i.e., a feature needed by several components.
