### ISSUE TITLE
Plan for a way to integrate a library into Joomla core

### ISSUE THREAD

**Issue by jochendaum** [joomla-projects/joomla-pythagoras#77]
I know of one extension that was very popular, but not able to be pursued by its owner to keep up with current Joomla development.

Unfortunately, it was abandoned and a completely new sub set of its functionality was build from scratch for Joomla core functionality.

I think the community would have benefited from this library being integrated into Joomla Core and the current solution is a step back.

My recommendation would be to develop a way to have open arms (and rules) for such extensions to be accepted "into the fold"

**Comment by nibra** [comment]
The decoupling throughout the system will make it possible to exchange, add or remove functionality easily.

Ideally, you choose during installation, if you want specific functionality, and if so, which implementation best suites you. That's something, we have in mind, and the UX team is already having a look at the feasibility (technically it is feasible, but can we provide a convenient user interface?)

**Comment by nibra** [comment]
No action required, closing.
