### ISSUE TITLE
Remove JSession dependency from JUser::save()

### ISSUE THREAD

**Issue by mbabker** [joomla-projects/joomla-pythagoras#8]
`JUser::save()` has an internal dependency to `JSession` via `JFactory::getSession()` to reload the cached `JUser` object in the session when the user updates their own profile data.  This forces the user object to have an awareness of the session and because of the internals of `JFactory` will force a session to be created if one is not already (i.e. a command line user management script or the unit test suite).  The save method needs to have this internal coupling removed; resetting the session data should be performed as an addon behavior via a plugin or in calling methods (components).

**Comment by nikosdion** [comment]
Plugin. Otherwise every single component going through JUser needs to
duplicate the same snippet of code which creates a whole lot of interesting
issues in the long run.

**Comment by mbabker** [comment]
Plugin's definitely preferred, just saying it's gotta move somewhere when all is said and done :smiley:

**Comment by laoneo** [comment]
@wilsonge is this issue planed for Joomla 4? Or can it even be done on a Joomla 3 minor release?

If yes, @mbabker can you please open (or transfer) this issue on (to) the CMS repo. It should be assigned then to the relevant milestone.

I'm closing this one as it is not relevant for Joomla X.

**Comment by wilsonge** [comment]
J4
