### ISSUE TITLE
Define Language String Deprecation

### ISSUE THREAD

**Issue by nibra** [joomla-projects/joomla-pythagoras#94]
Over time, the language files grow and grow. Some (core) extensions redefine language strings that already exist globally.

We need a mechanism to deprecate language strings (and suggest alternatives), as we have for classes and methods, so language strings can be removed safely.

This is related to issue #67 and PR #80.

**Comment by Bakual** [comment]
For translation tools like Crowdin, it's best to add a comment with the deprecation notice behind the string on the same line. This way it will show up in those tools as "context" information.

**Comment by nibra** [comment]
So 
`COM_USERS_OR="or" ; @deprecated 4.0 Use J_OR instead`
would work?

**Comment by brianteeman** [comment]
for crowdin yes - probably not on other platforms or for manual translators

On 2 June 2016 at 15:59, Niels Braczek notifications@github.com wrote:

> So
> COM_USERS_OR="or" ; @deprecated Use J_OR instead
> would work?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/joomla-projects/joomla-pythagoras/issues/94#issuecomment-223318599,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABPH8RJB0AIqlZBmac4D5zB8DvHjuZkeks5qHu_PgaJpZM4Isnih
> .

## 

Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by nibra** [comment]
Comments should work for manual translation as well. What other platforms do we need to consider?

**Comment by brianteeman** [comment]
You would think so but they will just end up translating the comment. Seen
too many existing translations sadly.

The real issue is should we even be deprecating them at all. I still
believe if it's not being used it should be removed and haven't heard a
good argument to keep them.

**Comment by nibra** [comment]
How do you know if it is used? Think of a 3PD module for com_users using the component's language file.

**Comment by brianteeman** [comment]
They should be using their own language strings. All deprecating before
removing will do is give you the opportunity to say "I told you so" it
won't notify them its deprecated or stop them following bad practice

(Obviously a jglobal string is different)

**Comment by nibra** [comment]
Notification would be possible, if `JHtml::_()` would check the state (in debug mode).

**Comment by brianteeman** [comment]
That assumes the developer who was too lazy to create their own strings
spent the time to check. History suggests they are not.

**Comment by nibra** [comment]
George Wilson mentioned on Twitter, that the [Unused Language String Locator](https://t.co/NgSxziNAgP) doesn't work for all the strings that are put together through string concat.

A special test suite could make sure, that no _used_ string gets removed.

**Comment by brianteeman** [comment]
Yeah any script will fail on those and produce false positives

**Comment by Bakual** [comment]
> for crowdin yes - probably not on other platforms or for manual translators

Afaik it also works this way for Transifex, but haven't tested it. For manual translators it would work as well for the more savvy translators :smile: . `com_localise` would have to be adjusted as it uses a different approach (I think the comment is on line before).

**Comment by mbabker** [comment]
> Notification would be possible, if JHtml::_() would check the state (in debug mode).

JLanguage doesn't have a parser to read INI comments (we're basically doing `parse_ini_string(file_get_contents($filename))` when parsing the files).  So you'd need a parser to extract comments and be able to match those comments to a line, and you'd probably need to account for both commenting styles:

``` sh
; @deprecated 4.0
JSTRING_WHATEVER="String Whatever"
JSTRING_WHY="String Why" ; @deprecated 4.0
```

JLanguage already has a debug mode attached to it so if such a parser is created you should just attach it there.  Also, [as done in the Framework](https://github.com/joomla-framework/language/commit/2da4017cbedfb5adeaeef935d590eabba1f52563), the debug parser should be extracted to a standalone method making it easier to run these checks.

**Comment by nibra** [comment]
Ole Bang Ottosen pointed out, that this has been discussed in depth at joomla/joomla-cms#9932.

**Comment by brianteeman** [comment]
Yes it has been discussed several times but never with any real conclusion

**Comment by nibra** [comment]
Well, I guess it is up to the PLT to make a decision.

**Comment by nibra** [comment]
Subject sent to PLT for decison. Closing.
