### ISSUE TITLE
[META] Clearly Define This Repository's Purpose

### ISSUE THREAD

**Issue by mbabker** [joomla-projects/joomla-pythagoras#95]
Clearly define this repository's purpose.  Is this the J4 repo?  JX?  Both?  Neither?

If this is the repository for J4, can the JX stuff be moved elsewhere?  Likewise if this is for only JX.

If this repo is for both, what measures are in place to ensure proper separations of concerns (as essentially J4 and JX are two different projects and as such should be maintained in two different repos)?

**Comment by brianteeman** [comment]
agreed - i am very confused especially with the "clean" branch
you cant have one project with two completely different branches as issues and pull requests are unclear

**Comment by nibra** [comment]
The Architecture Team is currently cleaning up this repo. It will be used for **Joomla X development**. All issues, branches, and PRs addressing the incremental development of Joomla 3/4 towards Joomla X will be moved to the CMS repo (either 'joomla/loomla-cms`or`joomla-projects/joomla-cms`, depending on PLT's decision) in the near future, so nothing of the valuable work done here gets lost.

After the cleanup, the `clean-base` branch will be renamed to `master`, so it will be evident for everybody, where to look for, try, test, and contribute to the lighthouse project.
